language: generic
# We need super permissions when dealing with docker
sudo: required
services: 
  - docker

# We need to build our docker image before our tests run.
before_install:
  - docker build -t root217/docker-react -f Dockerfile.dev .

# Contains the scripts needed to run the test suite.
script:
  - docker run -e CI=true root217/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-179855811867"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY